### ISSUE TITLE
unable to save api key

### ISSUE THREAD

**Issue by shark123567** [yikesinc/yikes-inc-easy-mailchimp-extender#323]
When I go into settings screen, API key space is blank but has error message " Sorry, that is an invalid MailChimp API key. Please check the error log on the debug options tab for further information. "

I copy Mailchimp API key into blank. (I have had MailChimp check, the API key is valid). The error message doesn't go away, and the SAVE button is not enabled.

Plugin Version
5.4.3 

Wordpress Version
4.2.2 

Browser Information
Unknown ? on Windows  

Server Information
Apache

**Comment by pamali** [comment]
same here

**Comment by pamali** [comment]
im resolved by deactivate > re activate the plugin and paste the api key, Save button can click now

**Comment by shark123567** [comment]
I deactivated the alligator pop up plugin and that seemed to the trick

**Comment by TeresaBe** [comment]
I tried deactivating and reactivating and it did not work the save settings button is still not available

**Comment by EvanHerman** [comment]
Hi,

I recommend that all of you try the latest beta version: https://cloudup.com/files/iqRJEg69slQ/download

The issue has been addressed in the upcoming release.

We will be rolling things out to the repository in the coming days, so its probably best to setup the new version now rather than setting things up and then transitioning to the new version.

Thanks,
Evan

**Comment by shark123567** [comment]
alligator pop up plugin  interferes with save button being activated

**Comment by EvanHerman** [comment]
@shark123556 in the version linked above?
