### ISSUE TITLE
Newsletter forms won't 'inline' 

### ISSUE THREAD

**Issue by Tettelestai** [yikesinc/yikes-inc-easy-mailchimp-extender#439]
I have toggled the inline forms to 'on' and the text fields align perfectly, but the submit button won't remain inline. Do you know how I can fix this?

**Comment by TheTracyL** [comment]
Can you please provide a link to your form?

Thank you!
-Tracy

**Comment by alexafox** [comment]
I'm having the same issue. I don't have recaptcha and I've tried both selecting the enable toggle and using the inline shortcode.

Here is a link to [my site](dev.chutefirstapparel.com/shop)

**Comment by TheTracyL** [comment]
Hi Alexafox,

I took a peek and the width of the area the form is in is narrow enough the cause the button to wrap below the email field.

This code will fix it for you:

`.yikes-easy-mc-form label.label-inline {
    width: calc( 100% - 30% );
}`

You have a few options to add CSS code:

<ul>
	<li>If you created this theme yourself, you can just add it to your style.css file</li>
	<li>If you're using a theme you downloaded or bought you can make a child theme and add the code to your child theme's style.css file</li>
	<li>Your theme may have a "Custom CSS" option. If it does, then you can just pop it in there.</li>
	<li>You can use a plugin like <a href="https://wordpress.org/plugins/simple-custom-css/">Simple Custom CSS</a> or Jetpack and enter the code in their Custom CSS area</li>
</ul>

**Comment by alexafox** [comment]
Thanks TheTracyL,

I've added the CSS code but it doesn't appear to be having any impact.

**Comment by TheTracyL** [comment]
I see your code it loading, but it's not getting priority. Please try adding !important.

Like this:

`.yikes-easy-mc-form label.label-inline {
    width: calc( 100% - 30% ) !important;
}`

Thank you!
-Tracy

**Comment by alexafox** [comment]
Perfect!

Thanks for your help and super quick reply!

**Comment by TheTracyL** [comment]
Yay!

Absolutely no problem, we are happy to help.

If you're enjoying the plugin and support, please consider leaving a review:
https://wordpress.org/support/view/plugin-reviews/yikes-inc-easy-mailchimp-extender?filter=5

Nice reviews make a plugin developer's day :-)

Thank you!
-Tracy

**Comment by alexafox** [comment]
Done! :)

**Comment by TheTracyL** [comment]
Thank you so much!

**Comment by VidhiMakwana** [comment]
Hi Tracy, I hope you can help me. I have the same issue. I added the shortcode with inline="1" and my form still shows up as block element. I tried everything, the solution you gave above sets the width to 70% and mine is already 70%. Above that, I tried checking width and all, it doesn't help. In fact, not only the button, but my whole form is showing up in block. Can you help?

Here's my [page's link](https://vidzmak.com/simplified-instagram-crash-course/).

**Comment by VidhiMakwana** [comment]
Hi Tracy, the issue got resolved after sometime. I don't know how. Maybe it was cached wrongly somewhere. Sorry for bothering. :)

**Comment by kpu23** [comment]
Hi @VidhiMakwana - all good! Let us know if you need anything else. We'd be happy to help 👍
